format_version = 1

[project]
name = "26-v2-r2-ind-mcu-chassis"
ioc_file = "26-v2-r2-ind-mcu-chassis.ioc"

[dependencies]
packages = [
    "Chassis::ControllerMaster",
    "ChassisLocalization::EKF",
    "ChassisLocalization::JustEncoder",
    "MotorDrivers::Controller",
    "MotorDrivers::DJI",
    "MotorDrivers::DM",
    "SensorGyro::HWT101CT",
    "SensorPressure::XGZP6847D",
    "Trajectory::HomingMotorTrajectory",
    "Trajectory::MotorTrajectory",
    "bsp::GPIO_Driver",
    "libs::CRC",
    "libs::RingBuffer",
    "protocol::UartRxSync",
    "services::I2CUpdateManager",
    "services::Watchdog",
    "traits",
    "utils",
]
