include_guard(GLOBAL)

# Generated by cpkg sync.
# Include this file from the root CMakeLists.txt of your STM32CubeMX project.
# Use wtr_link_packages(<target>) for plain target_link_libraries(...).
# Use wtr_link_packages_public(<target>) to link with PUBLIC scope.

set(WTR_MANAGED_REPOSITORIES
    BasicComponents
    ChassisController
    MotorDrivers
    Sensors
    TrajectoryControl
    VelocityProfile
)

set(WTR_MANAGED_PACKAGE_DIRS
    Modules/BasicComponents/libs/control/mit_pd
    Modules/MotorDrivers/core
    Modules/BasicComponents/libs/control/pid_motor
    Modules/MotorDrivers/controllers
    Modules/ChassisController/Core
    Modules/VelocityProfile/Core
    Modules/VelocityProfile/SCurve
    Modules/ChassisController/Controller/Master
    Modules/ChassisController/Localization/JustEncoder
    Modules/BasicComponents/libs/utils/ring_buffer
    Modules/BasicComponents/utils
    Modules/BasicComponents/bsp/can_driver
    Modules/BasicComponents/services/watchdog
    Modules/MotorDrivers/motors/DJI
    Modules/BasicComponents/libs/utils/fixed_map
    Modules/MotorDrivers/motors/DM
    Modules/BasicComponents/protocol/UartRxSync
    Modules/Sensors/gyro/HWT101CT
    Modules/BasicComponents/libs/control/pid_pd
    Modules/TrajectoryControl/MotorTrajectory
    Modules/BasicComponents/bsp/gpio_driver
    Modules/BasicComponents/libs/utils/crc
    Modules/BasicComponents/libs/traits
)

foreach(_wtr_package_dir IN LISTS WTR_MANAGED_PACKAGE_DIRS)
    if(NOT EXISTS "${CMAKE_CURRENT_LIST_DIR}/../${_wtr_package_dir}/CMakeLists.txt")
        message(FATAL_ERROR "Missing managed package '${CMAKE_CURRENT_LIST_DIR}/../${_wtr_package_dir}'. Run cpkg sync.")
    endif()

    add_subdirectory(
        "${CMAKE_CURRENT_LIST_DIR}/../${_wtr_package_dir}"
        "${CMAKE_BINARY_DIR}/cpkg/${_wtr_package_dir}"
    )
endforeach()

set(WTR_DIRECT_PACKAGE_TARGETS
    Chassis::ControllerMaster
    ChassisLocalization::JustEncoder
    MotorDrivers::Controller
    MotorDrivers::DJI
    MotorDrivers::DM
    SensorGyro::HWT101CT
    Trajectory::MotorTrajectory
    bsp::GPIO_Driver
    libs::CRC
    libs::RingBuffer
    protocol::UartRxSync
    services::Watchdog
    traits
    utils
)

set(WTR_RESOLVED_PACKAGE_TARGETS
    libs::MIT_PD
    MotorDrivers::Core
    libs::PIDMotor
    MotorDrivers::Controller
    Chassis::Core
    VelocityProfile::Core
    VelocityProfile::SCurve
    Chassis::ControllerMaster
    ChassisLocalization::JustEncoder
    libs::RingBuffer
    utils
    bsp::CANDriver
    services::Watchdog
    MotorDrivers::DJI
    libs::FixedMap
    MotorDrivers::DM
    protocol::UartRxSync
    SensorGyro::HWT101CT
    libs::PID_PD
    Trajectory::MotorTrajectory
    bsp::GPIO_Driver
    libs::CRC
    traits
    FreeRTOS
    stm32cubemx
)

add_library(wtr_project_dependencies INTERFACE)
target_link_libraries(wtr_project_dependencies INTERFACE ${WTR_DIRECT_PACKAGE_TARGETS})

function(wtr_link_packages target)
    target_link_libraries(${target} ${WTR_DIRECT_PACKAGE_TARGETS})
endfunction()

function(wtr_link_packages_public target)
    target_link_libraries(${target} PUBLIC ${WTR_DIRECT_PACKAGE_TARGETS})
endfunction()
