include_guard(GLOBAL)

# Generated by cpkg sync.
# Include this file from the root CMakeLists.txt of your STM32CubeMX project.
# Use wtr_link_packages(<target>) for plain target_link_libraries(...).
# Use wtr_link_packages_public(<target>) to link with PUBLIC scope.

set(WTR_MANAGED_REPOSITORIES
    BasicComponents
    ChassisController
    MotorDrivers
    Sensors
    TrajectoryControl
    VelocityProfile
)

set(WTR_MANAGED_PACKAGE_DIRS
    Modules/BasicComponents/bsp/gpio_driver
    Modules/BasicComponents/libs/utils/crc
    Modules/BasicComponents/libs/utils/ring_buffer
    Modules/BasicComponents/services/watchdog
    Modules/BasicComponents/protocol/UartRxSync
    Modules/BasicComponents/bsp/i2c_driver
    Modules/BasicComponents/services/i2c_update_manager
    Modules/BasicComponents/libs/traits
    Modules/BasicComponents/utils
    Modules/BasicComponents/libs/control/mit_pd
    Modules/MotorDrivers/core
    Modules/BasicComponents/libs/control/pid_motor
    Modules/MotorDrivers/controllers
    Modules/ChassisController/Core
    Modules/VelocityProfile/Core
    Modules/VelocityProfile/SCurve
    Modules/ChassisController/Controller/Master
    Modules/BasicComponents/libs/math/LinearAlgebra
    Modules/BasicComponents/libs/math/EKF
    Modules/Sensors/gyro/HWT101CT
    Modules/BasicComponents/libs/concurrency
    Modules/BasicComponents/libs/utils/deque
    Modules/ChassisController/Localization/EKF
    Modules/ChassisController/Localization/JustEncoder
    Modules/BasicComponents/bsp/can_driver
    Modules/MotorDrivers/motors/DJI
    Modules/BasicComponents/libs/utils/fixed_map
    Modules/MotorDrivers/motors/DM
    Modules/Sensors/pressure/XGZP6847D
    Modules/BasicComponents/libs/control/pid_pd
    Modules/TrajectoryControl/MotorTrajectory
    Modules/TrajectoryControl/HomingMotorTrajectory
)

foreach(_wtr_package_dir IN LISTS WTR_MANAGED_PACKAGE_DIRS)
    if(NOT EXISTS "${CMAKE_CURRENT_LIST_DIR}/../${_wtr_package_dir}/CMakeLists.txt")
        message(FATAL_ERROR "Missing managed package '${CMAKE_CURRENT_LIST_DIR}/../${_wtr_package_dir}'. Run cpkg sync.")
    endif()

    add_subdirectory(
        "${CMAKE_CURRENT_LIST_DIR}/../${_wtr_package_dir}"
        "${CMAKE_BINARY_DIR}/cpkg/${_wtr_package_dir}"
    )
endforeach()

set(WTR_DIRECT_PACKAGE_TARGETS
    bsp::GPIO_Driver
    libs::CRC
    libs::RingBuffer
    protocol::UartRxSync
    services::I2CUpdateManager
    services::Watchdog
    traits
    utils
    Chassis::ControllerMaster
    ChassisLocalization::EKF
    ChassisLocalization::JustEncoder
    MotorDrivers::Controller
    MotorDrivers::DJI
    MotorDrivers::DM
    SensorGyro::HWT101CT
    SensorPressure::XGZP6847D
    Trajectory::HomingMotorTrajectory
    Trajectory::MotorTrajectory
)

set(WTR_RESOLVED_PACKAGE_TARGETS
    bsp::GPIO_Driver
    libs::CRC
    libs::RingBuffer
    services::Watchdog
    protocol::UartRxSync
    bsp::I2CDriver
    services::I2CUpdateManager
    traits
    utils
    libs::MIT_PD
    MotorDrivers::Core
    libs::PIDMotor
    MotorDrivers::Controller
    Chassis::Core
    VelocityProfile::Core
    VelocityProfile::SCurve
    Chassis::ControllerMaster
    Math::LinearAlgebra
    Math::EKF
    SensorGyro::HWT101CT
    libs::Concurrency
    libs::Deque
    ChassisLocalization::EKF
    ChassisLocalization::JustEncoder
    bsp::CANDriver
    MotorDrivers::DJI
    libs::FixedMap
    MotorDrivers::DM
    SensorPressure::XGZP6847D
    libs::PID_PD
    Trajectory::MotorTrajectory
    Trajectory::HomingMotorTrajectory
    stm32cubemx
    FreeRTOS
)

add_library(wtr_project_dependencies INTERFACE)
target_link_libraries(wtr_project_dependencies INTERFACE ${WTR_DIRECT_PACKAGE_TARGETS})

function(wtr_link_packages target)
    target_link_libraries(${target} ${WTR_DIRECT_PACKAGE_TARGETS})
endfunction()

function(wtr_link_packages_public target)
    target_link_libraries(${target} PUBLIC ${WTR_DIRECT_PACKAGE_TARGETS})
endfunction()
